friends = []
f1=input("st-1: ")
f2=input("st-2: ")
f3=input("st-3: ")
f4=input("st-4: ")
f5=input("st-5: ")
f6=input("st-6: ")
friends.append(f1)
friends.append(f2)
friends.append(f3)
friends.append(f4)
friends.append(f5)
friends.append(f6)
friends.sort()
print(type(friends))
